### ISSUE TITLE
'image' not displaying properly in v0.22

### ISSUE THREAD

**Issue by cwatson** [lawremi/cairoDevice#1]
Hello, I have a GUI that plots a "nifti" image (brain MRI data) into a Cairo device (using the "image" function from the package "oro.nifti"). Its class is "nifti" and the main data I am interested in is a 91 x 109 x 91 matrix of grayscale values.

I had no issues with plotting before v0.22 (although I had only used a version up until 0.20). I have attached 2 pictures, the one labeled "bad" is from v0.22, and the other from v0.20. I can provide an RDA of the brain image if it will help.

I am running R v3.2.0 on a 64-bit CentOS 6 machine (but also see this issue on R v3.1).

Any thoughts?
![testbad](https://cloud.githubusercontent.com/assets/177027/8881584/24c08176-320f-11e5-9c64-14c4d7bca2ea.png)
![testgood](https://cloud.githubusercontent.com/assets/177027/8881586/286cf444-320f-11e5-8998-4aedb84291cd.png)

**Comment by lawremi** [comment]
I probably just need to revert 44a180a3e3b0119833382d4c5b1b966e4bddc2c3.

**Comment by lawremi** [comment]
Reverted that, so it should work in the next release.

**Comment by cwatson** [comment]
Thanks!
