### ISSUE TITLE
In cairo_pdf Right to left fonts like Arabic and Persian are disjointed and reversed

### ISSUE THREAD

**Issue by m-hoseini** [lawremi/cairoDevice#3]
Hello, 

When I save a plot containing rtl font as cairo_pdf, characters are disjointed and reversed. Example:

` library(Cairo)`
`cairo_pdf("test.pdf")`
`plot(0, main="سلام علیکم")`
`dev.off()`

The PDF output looks like this. Instead of "سلام علیکم" it prints "م‌ک‌ی‌ل‌ع م‌ا‌ل‌س"
![image](https://user-images.githubusercontent.com/37844191/48120646-f5f90480-e287-11e8-9534-96efe5496cb4.png)

**Comment by lawremi** [comment]
This is the repository for the cairoDevice package, but the example code uses the Cairo package. They are not the same package. Please report this to the Cairo maintainers. Btw, cairoDevice uses Pango for its font rendering, which should get this stuff right.

**Comment by m-hoseini** [comment]
Sorry for the mistake, but the same problem exists with cairoDevice:

`library(cairoDevice)`
`Cairo_pdf("test.pdf")`
`plot(0,main="سلام علیکم")`
`dev.off()`
 
and the PDF file looks like this. The characters are converted to strange boxes.

Thanks.
 
![image](https://user-images.githubusercontent.com/37844191/49103790-888e3180-f291-11e8-9854-aea6c0e368c8.png)

**Comment by lawremi** [comment]
I can't reproduce this on my system (the output looks fine to me, but I'm not familiar with arabic/persian). I think it's a font issue. Pango may be failing to find the font that R describes to it, for some reason.
