### ISSUE TITLE
About cairoDevice package install

### ISSUE THREAD

**Issue by march3032** [lawremi/cairoDevice#4]
The condition:CentOS6.8 gcc4.47 R-3.4.0 cairoDevice_2.12.tar.gz
when i R CMD INSTALL cairodevice Package and the error likes below:
**R
**demo
...
**testing if installed package can be loaded
Error:package or namespace load failed for 'cairoDevice';
.onLoad failed in loadNamespace() for 'cairoDevice',details:
call:fun(libname,pkgname)
error:GDK display not found -please make sure X11 is running
Error:load failed 
Execution halted
what should i do ,i also try to install some higher version cairoDevice package and failed like this

**Comment by lawremi** [comment]
Please let me know if that fix works, then I'll upload to CRAN.
